services:
  - type: web
    name: joey-ai-frontend-v2
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: .next
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: http://localhost:8000
